IdentityApp/Controllers/RoleController.cs
using IdentityApp.Data;
using IdentityApp.Models;
using IdentityApp.Utilities;
using IdentityApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IdentityApp.Controllers
{
    public class RoleController : Controller
    {
        private readonly AppDbContext _db;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(AppDbContext db, UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _db.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (model.Name is null)
            {
                ModelState.AddModelError("Name", "Role Name is required!");
            }
            if (ModelState.IsValid)
            {
                if (await _roleManager.RoleExistsAsync(model.Name))
                {
                    //error
                    TempData[Status.Error] = "Role already exists.";
                    return RedirectToAction(nameof(Index));
                }

                await _roleManager.CreateAsync(new IdentityRole() { Name = model.Name });
                TempData[Status.Success] = "Role created successfully";

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet("Role/Edit/{id}")]
        public IActionResult Edit(string id)
        {
            var role = _db.Roles.FirstOrDefault(u => u.Id == id);
            if (role == null)
            {
                TempData[Status.Error] = "Role not found.";
                return RedirectToAction(nameof(Index));
            }

            var editRoleVM = new EditRoleVM { Name = role.Name, OldName = role.Name, RoleId = role.Id };
            return View(editRoleVM);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditRoleVM model)
        {
            if (ModelState.IsValid)
            {
                var role = _db.Roles.FirstOrDefault(u => u.Id == model.RoleId);

                if (role == null)
                {
                    TempData[Status.Error] = "Role not found.";
                    return RedirectToAction(nameof(Index));
                }

                if (model.Name != model.OldName)
                {
                    var roleIsExist = await _roleManager.RoleExistsAsync(model.Name);
                    if (roleIsExist)
                    {
                        TempData[Status.Error] = "Role already exists.";
                        return RedirectToAction(nameof(Index));
                    }

                }

                role.Name = model.Name;
                role.NormalizedName = model.Name.ToUpper();
                var result = await _roleManager.UpdateAsync(role);
                TempData[Status.Success] = "Role updated successfully";

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            var role = _db.Roles.FirstOrDefault(u => u.Id == id);
            if (role == null)
            {
                TempData[Status.Error] = "Role not found.";
                return RedirectToAction(nameof(Index));
            }
            var userRolesForThisRole = _db.UserRoles.Where(u => u.RoleId == id).Count();
            if (userRolesForThisRole > 0)
            {
                TempData[Status.Error] = "Cannot delete this role, since there are users assigned to this role.";
                return RedirectToAction(nameof(Index));
            }
            await _roleManager.DeleteAsync(role);
            TempData[Status.Success] = "Role deleted successfully.";
            return RedirectToAction(nameof(Index));
        }


    }
}

IdentityApp/Controllers/UserController.cs
using IdentityApp.Data;
using IdentityApp.Models;
using IdentityApp.Utilities;
using IdentityApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace IdentityApp.Controllers
{
    public class UserController : Controller
    {
        private readonly AppDbContext _db;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(AppDbContext db, UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var userList = _db.AppUsers.ToList();
            //var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in userList)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                user.Role = String.Join(",", userRoles);
            }

            return View(userList);
        }

        [HttpGet]
        public async Task<IActionResult> ManageRole(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var existingUserRoles = await _userManager.GetRolesAsync(user);
            var model = new RolesVM()
            {
                User = user
            };

            foreach (var role in _roleManager.Roles)
            {
                var roleSelection = new RoleSelection
                {
                    RoleName = role.Name
                };

                if (existingUserRoles.Any(roleName => roleName == role.Name))
                {
                    roleSelection.IsSelected = true;
                }
                model.RoleList.Add(roleSelection);
            }

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRole(RolesVM rolesVM)
        {
            var user = await _userManager.FindByIdAsync(rolesVM.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var oldUserRoles = await _userManager.GetRolesAsync(user);
            var removingOldRoles = await _userManager.RemoveFromRolesAsync(user, oldUserRoles);

            if (!removingOldRoles.Succeeded)
            {
                TempData[Status.Error] = "Error while removing roles";
                return View(rolesVM);
            }

            var addRolesToUser = await _userManager.AddToRolesAsync(user, rolesVM.RoleList.Where(role => role.IsSelected).Select(role => role.RoleName));


            if (!addRolesToUser.Succeeded)
            {
                TempData[Status.Error] = "Error while adding roles";
                return View(rolesVM);
            }

            TempData[Status.Success] = "Roles assigned successfully";
            return RedirectToAction(nameof(Index));
        }


        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult LockUnlock(string userId)
        {
            var user = _db.AppUsers.FirstOrDefault(u => u.Id == userId);
            if (user == null)
            {
                return NotFound();
            }
            if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                //user is locked and will remain locked untill lockoutend time
                //clicking on this action will unlock them
                user.LockoutEnd = DateTime.Now;
                TempData[Status.Success] = "User unlocked successfully.";
            }
            else
            {
                //user is not locked, and we want to lock the user
                user.LockoutEnd = DateTime.Now.AddMonths(1);
                TempData[Status.Success] = "User locked successfully.";
            }
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public IActionResult Delete(string userId)
        {
            var user = _db.AppUsers.FirstOrDefault(u => u.Id == userId);
            if (user == null)
            {
                return NotFound();
            }
            _db.AppUsers.Remove(user);
            _db.SaveChanges();
            TempData[Status.Success] = "User deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var existingUserClaims = await _userManager.GetClaimsAsync(user);

            var model = new ClaimsVM()
            {
                User = user
            };

            foreach (Claim claim in ClaimStore.claimsList)
            {
                ClaimSelection userClaim = new ClaimSelection
                {
                    ClaimType = claim.Type
                };
                if (existingUserClaims.Any(c => c.Type == claim.Type))
                {
                    userClaim.IsSelected = true;
                }
                model.ClaimList.Add(userClaim);
            }

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserClaims(ClaimsVM claimsVM)
        {
            var user = await _userManager.FindByIdAsync(claimsVM.User.Id);

            if (user == null)
            {
                return NotFound();
            }

            var claims = await _userManager.GetClaimsAsync(user);
            var result = await _userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                TempData[Status.Error] = "Error while removing claims";
                return View(claimsVM);
            }

            result = await _userManager.AddClaimsAsync(user,
                claimsVM.ClaimList.Where(c => c.IsSelected).Select(c => new Claim(c.ClaimType, c.IsSelected.ToString()))
                );

            if (!result.Succeeded)
            {
                TempData[Status.Error] = "Error while adding claims";
                return View(claimsVM);
            }

            TempData[Status.Success] = "Claims updated successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

IdentityApp/Views/Shared/_FlashMessage.cshtml
@using IdentityApp.Utilities

@if (TempData[Status.Success] != null)
{
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<p>@TempData[Status.Success]</p>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}
else if (TempData[Status.Error] != null)
{
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<p>@TempData[Status.Error]</p>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}

IdentityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IdentityApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <partial name="_LoginNav" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IdentityApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IdentityApp/Views/Shared/_LoginNav.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<ul class="navbar-nav ms-auto">   
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link">Hello @UserManager.GetUserName(User)</span>
        </li>
        <li class="nav-item">
            <form id="logoutForm" method="post" class="form-inline" asp-controller="Account" asp-action="Logout">
                <button type="submit" class="btn nav-link">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
        </li>
    }
</ul>